[tool.black]
line-length = 100
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | sdist
    | venv
    | env
    | \.env
  )/
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
skip_gitignore = true